# Generated by Django 3.0.6 on 2020-05-05 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='customuser',
            name='field_name',
            field=models.ImageField(default='defaults/profile_image.png', upload_to='profile_images/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='followed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='followers',
            field=models.IntegerField(default=0),
        ),
    ]
