# Generated by Django 3.0.6 on 2020-05-05 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200505_0743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='comments',
            new_name='commentsCount',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='likes',
            new_name='likesCount',
        ),
        migrations.AddField(
            model_name='postlike',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liked_post', to='core.Post'),
        ),
        migrations.AlterUniqueTogether(
            name='postlike',
            unique_together={('post', 'owner')},
        ),
        migrations.RemoveField(
            model_name='postlike',
            name='postLike',
        ),
    ]
