# Generated by Django 3.0.6 on 2020-05-05 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200505_0801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='followed',
            new_name='followedCount',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='followers',
            new_name='followersCount',
        ),
    ]
