# Generated by Django 3.0.6 on 2020-05-05 15:16

import core.validators
import django.core.validators
from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_customuser_chatted_with'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='chatted_with',
            field=django_mysql.models.ListCharField(models.CharField(max_length=10), blank=True, default=[], max_length=200, null=True, size=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='followedCount',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(99999999), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='followersCount',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(99999999), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='defaults/profile_image.png', null=True, upload_to='profile_images/', validators=[core.validators.validate_image]),
        ),
    ]
